<?php
/**
 * Plugin Name: Robots.txt Override for AI Crawlers
 * Description: Optimize robots.txt to allow AI crawlers (GPTBot, ClaudeBot, etc.) while protecting sensitive WordPress directories
 * Version: 1.0.0
 * Code Snippets: true
 * Tags: seo, ai-crawlers, robots, googlebot, chatgpt, claude
 *
 * INSTRUCTIONS:
 * - Save this as a Code Snippet in WordPress admin (Snippets > Add New)
 * - Activate the snippet
 * - This will override the default robots.txt response via WordPress 'robots_txt' filter
 * - Supports all major search engines + AI bots (GPTBot, ClaudeBot, Google-Extended, PerplexityBot, etc.)
 * - Protects /wp-admin/, /wp-includes/, /wp-content/plugins/, /wp-content/cache/
 * - Allows public uploads (/wp-content/uploads/)
 * - References Yoast SEO sitemap
 *
 * AFFECTED:
 * - GET requests to /robots.txt
 * - WordPress 'robots_txt' filter (priority 99999, runs AFTER Yoast SEO)
 * - No database queries, pure text output
 */

add_filter( 'robots_txt', function( $output, $public ) {
	// Priority 99999: runs AFTER Yoast SEO to override its robots.txt
	// Only override if WordPress is public (not private)
	if ( ! $public ) {
		return $output;
	}

	$robots_content = "# Robots.txt for Studiokook\n";
	$robots_content .= "# Generated by Code Snippets: Robots.txt Override for AI Crawlers\n";
	$robots_content .= "# Last updated: " . current_time( 'Y-m-d H:i:s' ) . "\n\n";

	// Default rules for all bots
	$robots_content .= "User-agent: *\n";
	$robots_content .= "Allow: /\n";
	$robots_content .= "Disallow: /wp-admin/\n";
	$robots_content .= "Disallow: /wp-includes/\n";
	$robots_content .= "Disallow: /wp-content/plugins/\n";
	$robots_content .= "Disallow: /wp-content/cache/\n";
	$robots_content .= "Allow: /wp-content/uploads/\n";
	$robots_content .= "Allow: /wp-json/\n";
	$robots_content .= "Disallow: /trackback/\n";
	$robots_content .= "Disallow: /?s=\n";
	$robots_content .= "Disallow: /search/\n";
	$robots_content .= "Crawl-delay: 0\n\n";

	// Google Search Bot - explicit allow
	$robots_content .= "User-agent: Googlebot\n";
	$robots_content .= "Allow: /\n";
	$robots_content .= "Disallow: /wp-admin/\n";
	$robots_content .= "Disallow: /wp-includes/\n";
	$robots_content .= "Disallow: /wp-content/plugins/\n";
	$robots_content .= "Disallow: /wp-content/cache/\n\n";

	// Google-Extended (for AI Training)
	$robots_content .= "User-agent: Google-Extended\n";
	$robots_content .= "Allow: /\n\n";

	// Microsoft Bing
	$robots_content .= "User-agent: Bingbot\n";
	$robots_content .= "Allow: /\n";
	$robots_content .= "Disallow: /wp-admin/\n";
	$robots_content .= "Disallow: /wp-includes/\n\n";

	// OpenAI GPTBot (ChatGPT training)
	$robots_content .= "User-agent: GPTBot\n";
	$robots_content .= "Allow: /\n\n";

	// OpenAI ChatGPT User
	$robots_content .= "User-agent: ChatGPT-User\n";
	$robots_content .= "Allow: /\n\n";

	// Anthropic ClaudeBot
	$robots_content .= "User-agent: ClaudeBot\n";
	$robots_content .= "Allow: /\n\n";

	// Anthropic-ai (Anthropic AI training crawler)
	$robots_content .= "User-agent: Anthropic-ai\n";
	$robots_content .= "Allow: /\n\n";

	// Perplexity AI
	$robots_content .= "User-agent: PerplexityBot\n";
	$robots_content .= "Allow: /\n\n";

	// Apple Applebot-Extended (AI features)
	$robots_content .= "User-agent: Applebot-Extended\n";
	$robots_content .= "Allow: /\n\n";

	// Meta (Facebook/Instagram AI)
	$robots_content .= "User-agent: Meta-ExternalAgent\n";
	$robots_content .= "Allow: /\n\n";

	// ByteDance
	$robots_content .= "User-agent: Bytespider\n";
	$robots_content .= "Allow: /\n\n";

	// Common Crawl (CCBot)
	$robots_content .= "User-agent: CCBot\n";
	$robots_content .= "Allow: /\n\n";

	// Amazon Bot
	$robots_content .= "User-agent: Amazonbot\n";
	$robots_content .= "Allow: /\n\n";

	// Yoast SEO Sitemap (primary sitemap location)
	$robots_content .= "Sitemap: https://studiokook.ee/sitemap_index.xml\n";

	return $robots_content;
}, 99999, 2 );
